services:
  - type: web
    name: ykvs-ai-assistant-old-version
    runtime: node
    buildCommand: npm install && python3 -m pip install -r requirements.txt
    startCommand: node backend-node/server.js
    healthCheckPath: /healthz
    autoDeploy: true
